# Generated by Django 5.0.7 on 2024-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('disability', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('marital_status', models.CharField(max_length=50)),
                ('institution_attended_a', models.CharField(blank=True, max_length=255)),
                ('institution_attended_b', models.CharField(blank=True, max_length=255)),
                ('institution_attended_c', models.CharField(blank=True, max_length=255)),
                ('institution_attended_d', models.CharField(blank=True, max_length=255)),
                ('course_of_study_a', models.CharField(blank=True, max_length=255)),
                ('course_of_study_b', models.CharField(blank=True, max_length=255)),
                ('course_of_study_c', models.CharField(blank=True, max_length=255)),
                ('qualification_a', models.CharField(blank=True, max_length=255)),
                ('qualification_b', models.CharField(blank=True, max_length=255)),
                ('qualification_c', models.CharField(blank=True, max_length=255)),
                ('skill_a', models.CharField(blank=True, max_length=255)),
                ('skill_b', models.CharField(blank=True, max_length=255)),
                ('skill_c', models.CharField(blank=True, max_length=255)),
                ('experience_a', models.CharField(blank=True, max_length=255)),
                ('experience_b', models.CharField(blank=True, max_length=255)),
                ('experience_c', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
