# Generated by Django 5.0.7 on 2024-08-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='institution_attended_d',
        ),
    ]
